### ISSUE TITLE
add_package / download availability

### ISSUE THREAD

**Issue by kel-mo** [caddy-dns/desec#4]
caddy-dns/desec works well for me. It would be great if it were integrated with https://caddyserver.com/ so a custom binary could be downloaded and available for caddy add_package github.com/caddy-dns/desec

**Comment by znkr** [comment]
Glad to hear that it's working well for you.

Adding this module to http://caddyserver.com/download is an interesting idea, unfortunately I don't know how to do it. I spend a bit of time trying to figure it out, but I did not make any progress. 

@mholt, could you point me in the right direction?

**Comment by mholt** [comment]
Should be super easy! Go to "Account" on our site (create one if you don't have one yet) and then log in, and then click "Claim package".

**Comment by znkr** [comment]
Oh, that is super easy. Thank you very much :)
